//START: include
/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKIO_H
#define _MOCKIO_H

#include "IO.h"

void MockIO_Init(void);
void MockIO_Destroy(void);
void MockIO_Verify(void);

void IO_Read_ExpectAndReturn(ioAddress_t offset, ioData_t toReturn);
void IO_Write_Expect(ioAddress_t offset, ioData_t data);

#endif
//END: include
