#Set this to @ to keep the makefile quiet
SILENCE = @

#---- Outputs ----#
COMPONENT_NAME = Unity

#--- Inputs ----#
UNITY_HOME = .
CPP_PLATFORM = Gcc
PROJECT_HOME_DIR = .
PROJECT_TEST_DIR = .
CPP_PLATFORM = Gcc

SRC_DIRS = \
	src

TEST_SRC_DIRS = \
	$(UNITY_HOME)/testMain\
	$(UNITY_HOME)/tests\

MOCKS_SRC_DIRS = \

INCLUDE_DIRS =\
  include\
  
include $(UNITY_HOME)/build/MakefileWorker.mk

